# Configuration for the PyUp update bot

# Make one big PR every week
schedule: "every week"

# Do not search for requirement files...
search: False

# ... we specify them by hand:
requirements:
  - conda_xnt.yml:
      # update all dependencies and pin them
      update: all
      pin: True
