language: generic
dist: xenial

schedule: "every week"

services:
  - docker
script:
  - while sleep 9m; do echo "=====[ Build is still running after $SECONDS seconds ]====="; done &
  - docker build -t development .
  - kill %1