version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "weekly"
    ignored_updates:
      - match:
          # ignore new tensorflow updates as new versions require AVX2
          # https://github.com/XENONnT/base_environment/issues/433
          dependency_name: "tensorflow"
      - match:
          # tensorflow limits what versions of numpy we can use
          dependency_name: "numpy"
