name: 'Update context collection'
on:
  workflow_dispatch:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    container: xenonnt/base-environment:latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: checkout cutax
        uses: actions/checkout@v2
        with:
          repository: XENONnT/cutax
          token: ${{ secrets.CUTAX_TOKEN }}
      - name: Write utilix config
        run: |
            bash .github/scripts/create-utilix-config.sh
            cp ~/.xenon_config ./
        env:
          RUNDB_API_URL: ${{ secrets.RUNDB_API_URL }}
          RUNDB_API_USER: ${{ secrets.RUNDB_API_USER }}
          RUNDB_API_PASSWORD: ${{ secrets.RUNDB_API_PASSWORD }}
          PYMONGO_URL: ${{ secrets.PYMONGO_URL }}
          PYMONGO_USER: ${{ secrets.PYMONGO_USER }}
          PYMONGO_PASSWORD: ${{ secrets.PYMONGO_PASSWORD }}
          PYMONGO_DATABASE: ${{ secrets.PYMONGO_DATABASE }}