name: 'Test build'
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Run the test
          run: |
            ls
            pwd
            while sleep 9m; do echo "=====[ Build is still running after $SECONDS seconds ]====="; done &
            docker build -t development .
            kill %1
