name: 'Test build'
on:
  workflow_dispatch:
  release:
    types: [created]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: create key
        run: |
           mkdir ~/.ssh
           cat ${{ secrets.PRIVATE_KEY }} > ~/.ssh/id_rsa
      - name: Write utilix config
        run: |
            bash .github/scripts/create-utilix-config.sh
        env:
          RUNDB_API_URL: ${{ secrets.RUNDB_API_URL }}
          RUNDB_API_USER: ${{ secrets.RUNDB_API_USER }}
          RUNDB_API_PASSWORD: ${{ secrets.RUNDB_API_PASSWORD }}
          PYMONGO_URL: ${{ secrets.PYMONGO_URL }}
          PYMONGO_USER: ${{ secrets.PYMONGO_USER }}
          PYMONGO_PASSWORD: ${{ secrets.PYMONGO_PASSWORD }}
          PYMONGO_DATABASE: ${{ secrets.PYMONGO_DATABASE }}
      - name: Build container
        run: |
            while sleep 9m; do echo "=====[ Build is still running after $SECONDS seconds ]====="; done &
            docker build -t development .
            kill %1
